#ifndef GetPlayerUnitTypeCountIncluded
#define GetPlayerUnitTypeCountIncluded
library GetPlayerUnitTypeCount
native GetPlayerUnitTypeCount takes player p,integer unitid returns integer
endlibrary
#endif
